### ISSUE TITLE
Grampsweb v25.5.1 (Gramps 6) with PostgreSQL addon

### ISSUE THREAD

**Issue by bendikwa** [gramps-project/gramps-web-api#640]
When trying to use Grampsweb v25.5.1 (Gramps 6) with an external database using PostgreSQL addon it fails with:
ERROR: grampscli.py: line 207: Failed to open database.

It is unclear to me if this was expected to work or not, but since there was no warnings about it in the docs (https://www.grampsweb.org/install_setup/v3/) , I assumed it would.

Versions:
Grampsweb: v25.5.1
Gramps 6.0.1
Gramps Web API 3.0.0
Gramps Web Frontend 25.5.1

PostgreSQL version: 16 & 17

Log:
(__main__.py:7): Gtk-CRITICAL **: 08:54:58.431: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.
Current Gramps config setting: database.backend:'sqlite'
    New Gramps config setting: database.backend:'postgresql'
Current Gramps config setting: database.host:''
    New Gramps config setting: database.host:'grampsweb-psql'
Current Gramps config setting: database.port:''
    New Gramps config setting: database.port:'5432'

(gramps:1): Gtk-CRITICAL **: 08:55:01.229: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
2025-05-18 08:55:17.037: ERROR: grampscli.py: line 207: Failed to open database.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gramps/cli/grampscli.py", line 182, in read_file
    self.dbstate.db.load(
  File "/usr/local/lib/python3.11/dist-packages/gramps/gen/db/generic.py", line 740, in load
    if self.use_json_data():
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 91, in use_json_data
    return self.dbapi.column_exists("metadata", "json_data")
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute 'column_exists'
Opened successfully!
Importing: file /tmp/gramps-web-export.gramps, format gramps.
2025-05-18 08:55:17.054: ERROR: grampsapp.py: line 188: Unhandled exception
Traceback (most recent call last):
  File "/usr/local/bin/gramps", line 3, in <module>
    app.main()
  File "/usr/local/lib/python3.11/dist-packages/gramps/grampsapp.py", line 701, in main
    errors = run()
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps/grampsapp.py", line 693, in run
    startcli(error, argpars)
  File "/usr/local/lib/python3.11/dist-packages/gramps/cli/grampscli.py", line 379, in startcli
    handler.handle_args_cli()
  File "/usr/local/lib/python3.11/dist-packages/gramps/cli/arghandler.py", line 475, in handle_args_cli
    self.__import_action()
  File "/usr/local/lib/python3.11/dist-packages/gramps/cli/arghandler.py", line 546, in __import_action
    self.cl_import(imp[0], imp[1])
  File "/usr/local/lib/python3.11/dist-packages/gramps/cli/arghandler.py", line 602, in cl_import
    import_function(self.dbstate.db, filename, self.user)
  File "/usr/local/lib/python3.11/dist-packages/gramps/plugins/importer/importxml.py", line 185, in importData
    parser = GrampsParser(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps/plugins/importer/importxml.py", line 573, in __init__
    self.import_researcher = self.db.get_total() == 0
                             ^^^^^^^^^^^^^^^^^
AttributeError: 'DummyDb' object has no attribute 'get_total'

**Comment by DavidMStraub** [comment]
This should be fixed in the latest addon version - see https://github.com/gramps-project/addons-source/pull/725.

**Comment by bendikwa** [comment]
Can I upgrade the addon separately, or do I need to wait for the next Gampsweb release (v25.5.2)?
I Use the `ghcr.io/gramps-project/grampsweb` docker image.

**Comment by bendikwa** [comment]
Perfect! I can confirm that it worked for me. 🙏

**Comment by bendikwa** [comment]
Sorry to keep posting to this closed issue, but the fix is only partial for me. Let me know if you want me to open a new issue instead.

Using the `latest-devel`  version works for existing database backends, but not for importing/bootstrapping a new.
I am trying to create a new backend based on the method described in the [documentation](https://www.grampsweb.org/install_setup/postgres/#importing-a-gramps-family-tree).
It is working fine using `v25.4.1`, but when I try using the `latest-devel` it does not create the config for the tree on disk. At least not in the expected directory `/root/.gramps/grampsdb`. Even if the logs does not show any errors.

The two import job test runs have identical configuration, only the version is different.
```gramps -u -C tree -i /tmp/gramps-web-export.gramps --debug "" --config=database.backend:$(GRAMPSWEB_DATABASE_BACKEND) --config=database.host:$(GRAMPSWEB_DATABASE_HOST) --config=database.port:$(GRAMPSWEB_DATABASE_PORT) --username=$(GRAMPSWEB_POSTGRES_USER) --password=$(GRAMPSWEB_POSTGRES_PASSWORD)```

From the logs it looks like the initialization of the Postgres database works as intended, and the database itself is populated with tables.
Attached are the logs from runs with the two different versions, but I can't see any obvious errors. ( I have omitted some lines from `_dateparser.py` as well as quite a few transaction begin/commit statements for readability)


[v25.4.1.log](https://github.com/user-attachments/files/20361981/v25.4.1.log)

[latest-devel.log](https://github.com/user-attachments/files/20361985/latest-devel.log)

**Comment by DavidMStraub** [comment]
I think the problem here is that, annoyingly, Gramps 6.0 has changed the location of the default database path. To work around that, Web API now sets the config option to the old value: https://github.com/gramps-project/gramps-web-api/blob/master/gramps_webapi/app.py#L108-L111

When using `gramps` from the command line, it does not know about this setting. Please add `--config=database.path:/root/.gramps/grampsdb` and see if that works.

If it does, it would be awesome if you could submit a PR to the docs (for all occurrences of `gramps` CLI).
